name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone or pull the changes to repo
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_ROOT_USER }} # User of the server you want to ssh into
          port: 22
          script: |
            git -C online-ide pull || git clone git@github.com:adityaharsh2001/online-ide.git 
            docker system prune --all --force -y
            docker compose -f /root/online-ide/docker-compose.yml -p online_ide up --build --remove-orphans -d
            docker-compose -f /root/online-ide/docker-compose.yml stop -t 1
            echo 'Deployment successful to digital ocean'
    env:
      CI: true
      
